# Script taken from https://github.com/Bouni/kicad-jlcpcb-tools
# All credit belongs to them

name: KiCAD PCM packaging
on:  # yamllint disable-line rule:truthy
  release:
    branches: [main]
    types:
      - published
  workflow_dispatch:

jobs:
  create_archive:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
<<<<<<< HEAD
          repository: hlord2000/nordic-lib-kicad
=======
          repository: hlord2000/rpi-lib-kicad
>>>>>>> 7bc2cd3 (Initial commit.)
          releases-only: true
        id: latest-release

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create archive
        run: sh ./PCM/create_pcm_archive.sh ${{ steps.latest-release.outputs.tag }}

      - name: Upload zip as asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./PCM/KiCAD-PCM-${{ steps.latest-release.outputs.tag }}.zip
          asset_name: KiCAD-PCM-${{ steps.latest-release.outputs.tag }}.zip
          overwrite: true
          tag: ${{ steps.latest-release.outputs.tag }}

      - name: Trigger custom kicad repo rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Rebuild repository
          ref: refs/heads/main
          repo: hlord2000/hlord2000-kicad-repository
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "VERSION": "${{env.VERSION}}", "DOWNLOAD_SHA256": "${{env.DOWNLOAD_SHA256}}", "DOWNLOAD_SIZE": "${{env.DOWNLOAD_SIZE}}", "DOWNLOAD_URL": "${{env.DOWNLOAD_URL}}", "INSTALL_SIZE": "${{env.INSTALL_SIZE}}" }'
